#!/usr/bin/env python3

import json
import logging
import os
import sys

import requests
from common import (decrypt_body, encrypt_body, load_session, parse_args,
                    parse_env, update_session_sequence)
from crypto import (decrypt_aes256_cbc, ecdh_shared_key, encrypt_aes256_cbc,
                    generate_ec_keypair, load_pub_key, serialize_pub_key,
                    sha256_digest, verify_ecdsa)

logging.basicConfig(format="%(levelname)s\t- %(message)s")
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def encrypt_body_without_mac(body: bytes, secret_key: bytes) -> bytes:
    iv = os.urandom(16)
    return iv + encrypt_aes256_cbc(body, secret_key, iv)

def get_file(state, file_handle):
    ephemeral_priv_key, ephemeral_pub_key = generate_ec_keypair()
    server_pub_key = load_pub_key(state["REP_PUB_KEY"].encode("utf8"))
    secret_key = ecdh_shared_key(ephemeral_priv_key, server_pub_key, 32)
    serialized_pub_key = serialize_pub_key(ephemeral_pub_key)
    body = {
        "file_handle": file_handle
    }
    
    cipheredbody = encrypt_body_without_mac(json.dumps(body).encode("utf8"), secret_key)
    data = len(serialized_pub_key).to_bytes(2, "big") + serialized_pub_key + cipheredbody

    req = requests.get(f'http://{state["REP_ADDRESS"]}/files', data=data)

    if req.status_code == 200:
        body_len = int.from_bytes(req.content[:2], "big")
        body = req.content[2:2+body_len]
        signature = req.content[2+body_len:]

        if verify_ecdsa(server_pub_key, body, signature):
            return decrypt_aes256_cbc(secret_key, body[:16], body[16:])
        else:
            logger.error("Could not authenticate the server, response signature mismatch! Someone could be eavesdropping on you!")
            sys.exit(-1)
    else:
        logger.error(req.json())
        sys.exit(-1)

 # This commands requires a DOC_READ permission.
def main():
    state = parse_env({})
    positional_args = ["session_file", "document_name"]
    optional_args = ["file"]
    state = parse_args(state, positional_args, optional_args)

    if 'REP_ADDRESS' not in state:
        logger.error("Must define Repository Address")
        sys.exit(-1)

    if 'REP_PUB_KEY' not in state:
        logger.error("Must set the Repository Public Key")
        sys.exit(-1)

    session_file = state["session_file"]
    file = state["file"]

    session_id, seq, secret_key, mac_key = load_session(session_file)
    
    headers = {
        "sessionid": session_id
    }

    body = {
        "document_name": state["document_name"]
    }

    logger.info("Fetching document metadata...")

    body = encrypt_body(json.dumps(body).encode("utf8"), seq, secret_key, mac_key)

    req = requests.get(f'http://{state["REP_ADDRESS"]}/document_metadata', headers=headers, data=body)

    update_session_sequence(session_file)

    if req.status_code == 200:
        metadata = decrypt_body(req.content, secret_key, mac_key)
    else:
        if req.headers["content-type"] == "application/octet-stream":
            logger.error(json.loads(decrypt_body(req.content, secret_key, mac_key)))
        else:
            logger.error(req.json())

        sys.exit(-1)

    # Decrypt

    size = int.from_bytes(metadata[0:2], "big")
    json_metadata = json.loads(metadata[2:size+2])

    if json_metadata["crypto_alg"] != "AES256_CBC":
        print(f"Unsupported crypto algorithm in the metadata")
        sys.exit(1)

    if json_metadata["digest_alg"] != "SHA256":
        print(f"Unsupported digest algorithm in the metadata")
        sys.exit(1)

    secret_key = metadata[2+size:2+size+32]
    iv = metadata[2+size+32:]

    logger.info("Fetching file...")
    file_handle = json_metadata["file_handle"]

    ciphertext = get_file(state, file_handle)

    logger.info("Decrypting file...")
    plaintext = decrypt_aes256_cbc(secret_key, iv, ciphertext)

    if file_handle != sha256_digest(plaintext):
        print(f"Integrity verification failed!")
        sys.exit(1)

    if file != None : 
        with open(file, 'wb') as f:
            f.write(plaintext)
    else:
        sys.stdout.buffer.write(plaintext)
        sys.stdout.buffer.flush()


if __name__ == "__main__":
    main()
