"""empty message

Revision ID: bca017d1acb9
Revises: 652aa5cb31c9
Create Date: 2024-11-13 16:42:46.219754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca017d1acb9'
down_revision = '652aa5cb31c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.UUID(), nullable=False))
        batch_op.alter_column('org_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.create_foreign_key(None, 'subjects', ['creator_id'], ['id'])
        batch_op.drop_column('creator')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('org_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
