services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: repository

    ports:
      - "5432:5432"

    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
    restart: unless-stopped
    stop_signal: SIGINT
    
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@database:5432/repository
      MASTER_PASSWORD: $MASTER_PASSWORD

    ports:
      - "8000:8000"

volumes:
  db:
